print("Imprimir del '1' al '100'")
NUMERO_INICIAL = 1
NUMERO_FINAL = 100
INCREMENTO = 1
DIVISOR = 2

while NUMERO_INICIAL <= NUMERO_FINAL:
    if NUMERO_INICIAL % DIVISOR != 0:
        print(NUMERO_INICIAL)
    NUMERO_INICIAL += INCREMENTO